#!/bin/bash

# HTML2PNG Docker Deployment Script
# This script helps you deploy HTML2PNG with Docker

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                                                           ║"
echo "║            HTML2PNG Docker Deployment Script              ║"
echo "║                                                           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed. Please install Docker first.${NC}"
    exit 1
fi

# Check if Docker Compose is installed
if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed. Please install Docker Compose first.${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Docker and Docker Compose are installed${NC}"
echo ""

# Navigate to docker directory
cd "$(dirname "$0")/docker"

# Check if .env already exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}An existing .env file was found.${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo -e "${CYAN}Keeping existing configuration.${NC}"
        echo ""
    else
        rm -f .env
    fi
fi

# Generate .env file if it doesn't exist
if [ ! -f ".env" ]; then
    echo -e "${CYAN}Let's configure your HTML2PNG instance.${NC}"
    echo ""

    # Admin Email
    echo -e "${YELLOW}1. Admin Account${NC}"
    echo "   This account will be created on first startup."
    read -p "   Admin Email [admin@example.com]: " admin_email
    admin_email=${admin_email:-admin@example.com}
    echo ""

    # Admin Password
    while true; do
        read -s -p "   Admin Password (min 8 characters): " admin_password
        echo ""
        if [ ${#admin_password} -lt 8 ]; then
            echo -e "   ${RED}Password must be at least 8 characters${NC}"
        else
            break
        fi
    done
    echo ""

    # Port
    echo -e "${YELLOW}2. Server Port${NC}"
    read -p "   Port [3000]: " port
    port=${port:-3000}
    echo ""

    # Create .env file
    cat > .env << EOF
# HTML2PNG Configuration
# Generated by deploy.sh

# Admin account credentials
ADMIN_EMAIL=${admin_email}
ADMIN_PASSWORD=${admin_password}

# Server port (change if 3000 is already in use)
PORT=${port}
EOF

    echo -e "${GREEN}✓ Configuration saved to docker/.env${NC}"
    echo ""
fi

# Update docker-compose port if needed
if [ -n "$port" ] && [ "$port" != "3000" ]; then
    # Check if we're on macOS or Linux for sed compatibility
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s/\"3000:3000\"/\"${port}:3000\"/" docker-compose.yml
    else
        sed -i "s/\"3000:3000\"/\"${port}:3000\"/" docker-compose.yml
    fi
fi

# Build and start
echo -e "${CYAN}Building and starting HTML2PNG...${NC}"
echo ""

if docker compose version &> /dev/null; then
    docker compose up -d --build
else
    docker-compose up -d --build
fi

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                                                           ║${NC}"
echo -e "${GREEN}║            HTML2PNG deployed successfully!                ║${NC}"
echo -e "${GREEN}║                                                           ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "   ${CYAN}URL:${NC}      http://localhost:${port:-3000}"
echo -e "   ${CYAN}Admin:${NC}    ${admin_email:-admin@example.com}"
echo ""
echo -e "   ${YELLOW}Note: Registration is disabled by default.${NC}"
echo -e "   ${YELLOW}Login as admin and enable it in the Admin panel if needed.${NC}"
echo ""
echo -e "   ${CYAN}Useful commands:${NC}"
echo "   - View logs:     docker logs -f html2png"
echo "   - Stop service:  docker stop html2png"
echo "   - Start service: docker start html2png"
echo "   - Remove:        docker rm -f html2png"
echo ""
